apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: hawktrace-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: collector
          image: ghcr.io/francisco-teixeirax86/hawktrace-collector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.hawktrace-storage:9092"
            - name: HAWKTRACE_KAFKA_TOPIC_LOGS
              value: "hawktrace.logs"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: hawktrace-ingestion
spec:
  type: NodePort
  selector:
    app: collector
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
